// In This first section I declared the constant of the game
var buttonColors = ["red", "blue", "green", "yellow"];
var gamePattern = [];
var userClickedPattern = [];

var startGame = true;
var level = 0;

// This line starts the game
document.querySelector("body").addEventListener("keydown",nextSequence,{once:true});

// This function changes the h1, then generates a new colour from the buttonColors arrays,
// blinks the button chosen and plays its audio
function nextSequence(){
    userClickedPattern = [];
    level++
    $("#level-title").text("Level "+level)
    var randomNumber = Math.round(Math.random() *3);
    var randomChosenColor = buttonColors[randomNumber];
    gamePattern.push(randomChosenColor);
    $("#" + randomChosenColor).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100);
    var audio = new Audio("sounds/"+randomChosenColor + ".mp3");
    audio.play();
};

// This Function changes the shadow of the button on and off tho show a blinking signal
function animatePress(currentColour){
    var self = $("."+currentColour).addClass("pressed");
    setTimeout(function(){
        self.removeClass("pressed");
    }, 100);
};

// This function calls the next sequence after 1 sec if the user get the pattern of the last question
function nextAfter1(){
    setTimeout(function(){
        nextSequence();
}, 1000);
};

// This function remove the red background after 0.2 seconds. 
// I added the red background to show the user that he missed the last question 
function gameOver(){
    setTimeout(function(){
        $("body").removeClass("game-over")
}, 200)
};

// This function restarts the game and reset all begining variables
function startOver(){
    gamePattern = [];
    userClickedPattern = [];
    level = 0;
    document.querySelector("body").addEventListener("keydown",nextSequence,{once:true});
}

// This was the most dificult part for me. 
// Here i checked the user click against the pattern generated by the computer
// If its correct I display another sequence but if its wrong I restart the game.
function checkAnswer(lastPress){
    if(userClickedPattern[lastPress] === gamePattern[lastPress]){
        if (userClickedPattern.length === gamePattern.length){
            nextAfter1();
    };  
    }else{
        var audio = new Audio ("sounds/wrong.mp3");
        audio.play();
        $("body").addClass("game-over")
        gameOver();
        $("#level-title").text("Game over, Press Any Key to Start");
        startOver()
    }   
};

// This part keeps listening for clicks from the user.
// It checks the clicks against the gamepattern in the checkAnswer function
$(".btn").on("click" , function(event){
    var userChosenColor = event.target.id;
    userClickedPattern.push(userChosenColor);
    animatePress(userChosenColor);
    var audio = new Audio("sounds/"+ event.target.id + ".mp3");
    audio.play();
    checkAnswer(userClickedPattern.length -1)
});



